name: Coverity Scan

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  coverity:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.400'

      - name: Restore dependencies
        run: dotnet restore

      - name: Download Coverity Tools
        run: |
          Invoke-WebRequest -Uri https://scan.coverity.com/download/cxx/windows64 \
            -OutFile coverity_tool.zip -Headers @{Authorization=("token " + "${{ secrets.COVERITY_SCAN_TOKEN }}")}
          Expand-Archive -Path coverity_tool.zip -DestinationPath coverity

      - name: Run Coverity Build
        run: |
          .\coverity\cov-analysis-win64-*.*.*\bin\cov-build.exe --dir cov-int dotnet build CoverityTestProject.csproj --configuration Release
          tar -czf coverity-scan.tgz cov-int

      - name: Upload to Coverity
        run: |
          curl --form token=${{ secrets.COVERITY_SCAN_TOKEN }} `
               --form email=${{ secrets.COVERITY_SCAN_EMAIL }} `
               --form file=@coverity-scan.tgz `
               --form version="1.0" `
               --form description="Simple C# Console App Coverity Scan" `
               https://scan.coverity.com/builds?project=your-github-username%2FCoverityTestProject
