name: Coverity Scan

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  coverity:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.400'

      - name: Restore dependencies
        run: dotnet restore

      - name: Download Coverity Tools
        run: |
          $headers = @{ Authorization = "token ${{ secrets.COVERITY_SCAN_TOKEN }}" }
          Invoke-WebRequest -Uri "https://scan.coverity.com/download/cxx/windows64" -OutFile "coverity_tool.zip" -Headers $headers
          Expand-Archive -Path "coverity_tool.zip" -DestinationPath "coverity"

      - name: Run Coverity Build
        run: |
          $covPath = Get-ChildItem -Path "coverity" -Directory | Select-Object -First 1
          & ".\coverity\$($covPath.Name)\bin\cov-build.exe" --dir cov-int dotnet build CoverityTestProject.csproj --configuration Release
          Compress-Archive -Path cov-int -DestinationPath coverity-scan.zip

      - name: Upload to Coverity
        run: |
          curl --form token=${{ secrets.COVERITY_SCAN_TOKEN }} `
               --form email=${{ secrets.COVERITY_SCAN_EMAIL }} `
               --form file=@coverity-scan.zip `
               --form version="1.0" `
               --form description="Simple C# Console App Coverity Scan" `
               https://scan.coverity.com/builds?project=Jubayer38%2FCoverityTestProject
